export const LOAD_USER = "LOAD_USER";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_COLLAPSE_RAW_INGREDIENTS = "SET_COLLAPSE_RAW_INGREDIENTS";
export const SET_COLLAPSE_PKG_INGREDIENTS = "SET_COLLAPSE_PKG_INGREDIENTS";
export const SET_COLLAPSE_RAW_STOCK = "SET_COLLAPSE_RAW_STOCK";
export const SET_COLLAPSE_PKG_STOCK = "SET_COLLAPSE_PKG_STOCK";
export const SET_COLLAPSE_PRODUCT = "SET_COLLAPSE_PRODUCT";
export const SET_COLLAPSE_NEXT_PRODUCT = "SET_COLLAPSE_NEXT_PRODUCT";

export const SET_OPEN_SIDEBAR = "SET_OPEN_SIDEBAR";
export const REMOVE_OPEN_SIDEBAR = "REMOVE_OPEN_SIDEBAR";

export const LOAD_USERS = "LOAD_USERS"
export const ADD_USER = "ADD_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USERS = "DELETE_USERS"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const OPEN_FORM = "OPEN_FORM"
export const CLOSE_FORM = "CLOSE_FORM"